# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# NV-pairs voor Nipper
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
toolbox: "g:/R_proj_gergiev/salsa_toolbox_r/src/salsa_toolbox.R"
uitzendmac_gewijzigd: FALSE
filemaker_gewijzigd: FALSE
# nipper_werk: "/Users/nipper/r_projects/cz_nipper/resources/nipper_werk.tab"
# home_draaiboeken: "//MACSERVER/Server RAID disk/Shared Items/Kantoor/PROGRAMMAS/Presentatie&Techniek/Programmaformulieren/01_nipper_draaiboeken"
home_draaiboeken: "//192.168.1.81/Server RAID disk/Shared Items/Kantoor/PROGRAMMAS/Presentatie&Techniek/Programmaformulieren/01_nipper_draaiboeken/"
# nip_xpr_gd_reg: "Nipper Express 0.2.FoSa"
nip_nxt_gd_reg: "NipperNext"

# host: "logmac"
host: "uitzendmac"

url_pfx: "docs.google.com/spreadsheets/d/"
url_nipper_next: "1U1aKx5CgZXfuQ3p491PFWKZWSE2TL87m1RErdleuMvQ"

cz_rds_store: "C:/Users/nipper/cz_rds_store/branches/cz_gdrive/"
gs_downloads: "C:/Users/nipper/Downloads/cz_downloads"

home_vt_audio.marcomac: "/Volumes/Data/"
home_vt_audio_mac.logmac: "/Volumes/Log schijf/" # _mac = om directory te gebruiken
home_vt_audio_win.logmac: "//LOGMAC/Log schijf/" # _win = om directory te maken
home_vt_audio_mac.uitzendmac: "/Volumes/Avonden/"
home_vt_audio_win.uitzendmac: "//UITZENDMAC-CZ/Avonden/"

home_radiologik.marcomac: "/Volumes/Systeem/Users/Tech/Music/Radiologik/"
home_radiologik.logmac: "//LOGMAC/Radiologik--preview/"
# home_radiologik.uitzendmac: "//UITZENDMAC-CZ/Radiologik--preview/"
home_radiologik.uitzendmac: "//UITZENDMAC-CZ/Radiologik/"

home_fonotheek.marcomac: "/Volumes/Data/fonotheek_sample/"
home_fonotheek.logmac: "/Volumes/Log schijf/fonotheek_sample/"
home_fonotheek.uitzendmac: "/Volumes/cz archief 01/"

home_schedulerswitch.logmac: "//LOGMAC/tech/Documents/Salsa/nipper_ctl"
home_schedulerswitch.uitzendmac: "//UITZENDMAC-CZ/tech/Documents/Salsa/nipper_ctl/"

# gids_samenvatting: "Van Lully in de Lente tot Kurt Weill in de Winter.<br><br>Muziek uit het Rijk van Randewijk.<!--more-->"
